import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // CollabOps Documentation Sidebar
  docs: [
    // Introduction Section
    {
      type: 'category',
      label: '📖 Introduction',
      collapsed: false,
      items: [
        'intro',
      ],
    },

          // Getting Started Section
      {
        type: 'category',
        label: '🚀 Getting Started',
        collapsed: false,
        items: [
          'getting-started',
          'deployment-guide',
          'analytics-guide',
        ],
      },

    // API Reference Section
    {
      type: 'category',
      label: '🔌 API Reference',
      collapsed: true,
      items: [
        'api/index',
        'api/authentication',
        // Future API docs can be added here:
        // 'api/endpoints',
        // 'api/webhooks', 
        // 'api/sdks',
      ],
    },

    // Self-Hosting Section
    {
      type: 'category',
      label: '🏠 Self-Hosting',
      collapsed: true,
      items: [
        'self-hosting/index',
        'self-hosting/helm',
        // Future self-hosting docs can be added here:
        // 'self-hosting/docker',
        // 'self-hosting/configuration',
        // 'self-hosting/troubleshooting',
      ],
    },

    // FAQ Section
    {
      type: 'category',
      label: '❓ FAQ',
      collapsed: true,
      items: [
        'faq/index',
        'faq/common',
        // Future FAQ docs can be added here:
        // 'faq/troubleshooting',
        // 'faq/billing',
      ],
    },
  ],

  // Alternative sidebar configuration (if needed for different sections)
  /*
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
  */
};

export default sidebars;
